### ISSUE TITLE
Space efficiency decreases after porting to OpenJDK 17

### ISSUE THREAD

**Issue by xinyu-zheng** [mmtk/mmtk-openjdk#139]
After I port to OpenJDK 17, MMTk's GCs become less space-efficient compared to how their parallel GC changes from 11 to 17. 
These are the raw results I get from running `minheap` for 3 and 5 iterations (note that `minheap` is not handling crashes well so there are some bad numbers):
3 iterations:
```
build-11-1007c9c.ms.s.c2.hotspot_gc-Parallel:
  dacapochopin-29a657f:
    avrora: 7
    batik: 313
    fop: 21
    jython: 69
    lusearch: 21
    pmd: 316
    sunflow: 41
    xalan: 18
build-11-2355c52-ddf0ba5-6dc618e.ms.s.c2.mmtk_gc-GenImmix.tph:
  dacapochopin-29a657f:
    avrora: 11
    batik: 365
    fop: 58
    jython: 112
    lusearch: 33
    pmd: .inf
    sunflow: 39
    xalan: 23
build-11-2355c52-ddf0ba5-6dc618e.ms.s.c2.mmtk_gc-Immix.tph:
  dacapochopin-29a657f:
    avrora: 10
    batik: 419
    fop: 29
    jython: 92
    lusearch: 29
    pmd: 298
    sunflow: 50
    xalan: 23
build-11-2355c52-ddf0ba5-6dc618e.ms.s.c2.mmtk_gc-SemiSpace.tph:
  dacapochopin-29a657f:
    avrora: 14
    batik: 608
    fop: 43
    jython: 120
    lusearch: 47
    pmd: 508
    sunflow: 54
    xalan: 60
build-17-2355c52-268dabd-818fc2c.ms.s.c2.mmtk_gc-GenImmix.tph:
  dacapochopin-29a657f:
    avrora: 14
    batik: 563
    fop: 44
    jython: 104
    lusearch: 33
    pmd: .inf
    sunflow: 54
    xalan: 25
build-17-2355c52-268dabd-818fc2c.ms.s.c2.mmtk_gc-Immix.tph:
  dacapochopin-29a657f:
    avrora: 15
    batik: 646
    fop: 31
    jython: 81
    lusearch: 28
    pmd: 296
    sunflow: 66
    xalan: 24
build-17-2355c52-268dabd-818fc2c.ms.s.c2.mmtk_gc-SemiSpace.tph:
  dacapochopin-29a657f:
    avrora: 22
    batik: 963
    fop: 45
    jython: 108
    lusearch: 45
    pmd: 501
    sunflow: 68
    xalan: 39
build-17-75240a5.ms.s.c2.hotspot_gc-Parallel:
  dacapochopin-29a657f:
    avrora: 7
    batik: 291
    fop: 21
    jython: 59
    lusearch: 21
    pmd: 288
    sunflow: 40
    xalan: 19
```
5 iterations:
```
build-11-1007c9c.ms.s.c2.hotspot_gc-Parallel:
  dacapochopin-29a657f:
    avrora: 7
    batik: 313
    fop: 21
    jython: 79
    lusearch: 21
    pmd: 313
    sunflow: 43
    xalan: 19
build-11-2355c52-ddf0ba5-6dc618e.ms.s.c2.mmtk_gc-GenImmix.tph:
  dacapochopin-29a657f:
    avrora: 10
    batik: 416
    fop: 39
    jython: 115
    lusearch: 41
    pmd: .inf
    sunflow: 130
    xalan: 3201
build-11-2355c52-ddf0ba5-6dc618e.ms.s.c2.mmtk_gc-Immix.tph:
  dacapochopin-29a657f:
    avrora: 11
    batik: 471
    fop: 30
    jython: 97
    lusearch: 35
    pmd: 300
    sunflow: 48
    xalan: 2050
build-11-2355c52-ddf0ba5-6dc618e.ms.s.c2.mmtk_gc-SemiSpace.tph:
  dacapochopin-29a657f:
    avrora: 15
    batik: 658
    fop: 43
    jython: 132
    lusearch: 59
    pmd: 501
    sunflow: 61
    xalan: 34
build-17-2355c52-268dabd-818fc2c.ms.s.c2.mmtk_gc-GenImmix.tph:
  dacapochopin-29a657f:
    avrora: 20
    batik: 614
    fop: 107
    jython: 114
    lusearch: 40
    pmd: .inf
    sunflow: 68
    xalan: 26
build-17-2355c52-268dabd-818fc2c.ms.s.c2.mmtk_gc-Immix.tph:
  dacapochopin-29a657f:
    avrora: 20
    batik: 694
    fop: 31
    jython: 84
    lusearch: 34
    pmd: 298
    sunflow: 83
    xalan: 25
build-17-2355c52-268dabd-818fc2c.ms.s.c2.mmtk_gc-SemiSpace.tph:
  dacapochopin-29a657f:
    avrora: 30
    batik: 1013
    fop: 45
    jython: 119
    lusearch: 56
    pmd: 514
    sunflow: 88
    xalan: 38
build-17-75240a5.ms.s.c2.hotspot_gc-Parallel:
  dacapochopin-29a657f:
    avrora: 7
    batik: 291
    fop: 21
    jython: 67
    lusearch: 21
    pmd: 290
    sunflow: 39
    xalan: 19
```
These might indicate the issue that my porting makes MMTk cost more memory to run or makes the memory leak more serious or both.
